# ---
# jupyter:
#   jupytext:
#     cell_metadata_filter: -all
#     formats: ipynb,py:percent
#     text_representation:
#       extension: .py
#       format_name: percent
#       format_version: '1.3'
#       jupytext_version: 1.19.1
#   kernelspec:
#     display_name: transformer312
#     language: python
#     name: python3
# ---

# %% [markdown]
# # Train and evaluate forecasting for the RatInABox synthetic rat
#
# Trains an agent-centric transformer on trajectories generated by a RatInABox
# reinforcement-learning agent. The model observes sensory-neuron firing rates
# (field-of-view boundary cells, head-direction cells) and predicts egocentric
# velocity.
#
# Requires a patched RatInABox -- see `environment/README.md`:
#
#     git clone -b speedup git@github.com:kristinbranson/RatInABox.git
#     pip install -e RatInABox
#
# The input trajectory pkls are produced separately; this notebook consumes them.

# %%
# %load_ext autoreload
# %autoreload 2
# %matplotlib inline

import os
import pickle
import time
import logging

import numpy as np
import torch
import matplotlib.pyplot as plt
import matplotlib.animation as animation
from matplotlib.colors import Normalize
import tqdm.auto as tqdm

import apf.dataset
import apf.models
import apf.utils as utils
from apf.io import get_modeltype_str, save_model, load_model, parse_modelfile
from apf.models import initialize_model, initialize_loss
from apf.training import train, init_optimizer

import experiments.synthrat as synthrat_exp
from synthrat import generate_data
from synthrat.config import read_config, DEFAULTCONFIGFILE
from synthrat.sensory import rehydrate_data
from synthrat.plotting import plot_episode

logging.basicConfig(level=logging.INFO)
LOG = logging.getLogger(__name__)

ISNOTEBOOK = utils.is_notebook()
if not ISNOTEBOOK:
    plt.ion()

LOG.info('CUDA available: ' + str(torch.cuda.is_available()))

# %% [markdown]
# ## Set parameters

# %%
configfile = DEFAULTCONFIGFILE
mode = 'train'                 # 'train' or 'test'
loadmodelfile = None           # set to a .pth to evaluate a trained model
restartmodelfile = None        # set to a .pth to resume training
outfigdir = 'figs'
debug_uselessdata = False      # True -> only a handful of episodes, for a quick smoke run
short_train_epochs = 200       # set to None to train for the full number of epochs

timestamp = time.strftime("%Y%m%dT%H%M%S", time.localtime())
print('Timestamp: ' + timestamp)

if outfigdir is not None and not os.path.exists(outfigdir):
    os.makedirs(outfigdir)

# %% [markdown]
# ## Load config and set up run state

# %%
config = read_config(configfile)
config['device'] = 'cuda' if torch.cuda.is_available() else 'cpu'

np.random.seed(config['numpy_seed'])
torch.manual_seed(config['torch_seed'])
device = torch.device(config['device'])
print('device:', device)

if short_train_epochs is not None:
    config['num_train_epochs'] = short_train_epochs

# %%

# %% [markdown]
# ## Build datasets
#
# Sensory firing rates are expensive to compute, so `make_dataset_cache_wrapper`
# caches them next to the input file and reuses them on later runs.

# %%
train_dataset, train_data, ratinabox_info = synthrat_exp.make_dataset_cache_wrapper(
    config['intrainfile'], config, debug_uselessdata)
val_dataset, val_data, _ = synthrat_exp.make_dataset_cache_wrapper(
    config['invalfile'], config, debug_uselessdata)

# info dicts -> live RatInABox objects, needed by the debug plots
ratinabox_info = rehydrate_data(ratinabox_info)

train_dataloader = apf.dataset.DataLoader(
    train_dataset, batch_size=config['batch_size'], shuffle=True, pin_memory=True)
val_dataloader = apf.dataset.DataLoader(
    val_dataset, batch_size=config['batch_size'], shuffle=False, pin_memory=True)

print(f'{len(train_dataset)} train chunks, {len(val_dataset)} val chunks')
print(f'd_input={train_dataset.d_input}, '
      f'd_output_continuous={train_dataset.d_output_continuous}, '
      f'd_output_discrete={train_dataset.d_output_discrete}, '
      f'nbins={train_dataset.discretize_nbins}')
print('inputs:', {k: v for k, v in train_dataset.input_idx.items()})

# %%
# Feature names for each input and label dimension, useful for probing/attribution.
input_names = train_dataset.get_input_names()
label_names = train_dataset.get_label_names()
print(f'{len(input_names)} inputs, e.g.:')
for nm in input_names[:3] + input_names[-3:]:
    print('   ', nm)
print(f'{len(label_names)} labels, e.g.: {label_names[:2]}')

# %% [markdown]
# ## Initialize model

# %%
model, criterion = initialize_model(config, train_dataset, device)

if config.get('model_nickname') is not None:
    modeltype_str = config['model_nickname']
else:
    modeltype_str = get_modeltype_str(config)

num_training_steps = config['num_train_epochs'] * len(train_dataloader)
optimizer, lr_scheduler = init_optimizer(num_training_steps, model, config['optimizer_args'])

if loadmodelfile is not None:
    modeltype_str, savetime = parse_modelfile(loadmodelfile)
    loss_epoch = load_model(loadmodelfile, model, device)
    epoch = config['num_train_epochs']
elif restartmodelfile is not None:
    savetime = timestamp
    loss_epoch = load_model(restartmodelfile, model, device,
                            lr_optimizer=optimizer, scheduler=lr_scheduler)
    epoch = int(np.sum(~np.isnan(loss_epoch['train'].cpu().numpy())))
else:
    savetime = timestamp
    loss_epoch = initialize_loss(train_dataset, config)
    epoch = 0

savefilestr = os.path.join(config['savedir'], f'synthrat_{modeltype_str}_{savetime}')
os.makedirs(config['savedir'], exist_ok=True)
print(f'model type: {modeltype_str}, starting from epoch {epoch}')
print(f'checkpoints -> {savefilestr}_epoch<epoch>.pth')

# %% [markdown]
# ## Set up debug plots
#
# One figure shows a batch of trajectories with their sensory inputs (and, during
# training, the predicted trajectory overlaid); the other tracks the losses.

# %%
from IPython.display import display

hdebug = {
    'train': synthrat_exp.initialize_debug_plots(
        train_dataset, train_dataloader, ratinabox_info, name='Train', nplot=3),
    'val': synthrat_exp.initialize_debug_plots(
        val_dataset, val_dataloader, ratinabox_info, name='Val', nplot=3),
}
hloss = synthrat_exp.initialize_loss_plots(loss_epoch)

# Under %matplotlib inline a figure is a one-shot static PNG: mutating it later and
# calling plt.show() does not re-render it. Live updates must go through
# display(fig, display_id=..., update=True), which replaces that figure's output cell
# in place. Close the freshly created figures first so inline does not also emit a
# static copy of each at cell end; refresh_plots then drives all rendering.
if ISNOTEBOOK:
    for h in (hdebug['train'], hdebug['val'], hloss):
        for k, fig in h.items():
            if k.startswith('fig') and fig is not None:
                plt.close(fig)


def refresh_plots(h, prefix):
    """Redraw every figure in h, updating its output cell in place in a notebook.

    h is a debug/loss handle dict; any value under a key starting with 'fig' is
    treated as a Figure. The first display for a given (prefix, key) registers a
    stable display_id; later calls reuse it with update=True to redraw in place.
    """
    seen = h.setdefault('_displayed', set())
    for k, fig in h.items():
        if not k.startswith('fig') or fig is None:
            continue
        fig.canvas.draw_idle()
        if ISNOTEBOOK:
            display(fig, display_id=f'{prefix}__{k}', update=(k in seen))
            seen.add(k)
        else:
            fig.canvas.flush_events()


# Initial render (registers the display_ids the hooks will update in place).
refresh_plots(hdebug['train'], 'train')
refresh_plots(hdebug['val'], 'val')
refresh_plots(hloss, 'loss')

# Hold one raw batch per split so every refresh redraws the same examples.
# update_debug_plots wants the raw batch dict (with 'input' / 'metadata'), not the
# Data-dict form that initialize_debug_plots keeps.
debug_batches = {
    'train': next(iter(train_dataloader)),
    'val': next(iter(val_dataloader)),
}


# %%
def predict_on(batch):
    """Run the model on one raw batch dict, returning its output dict."""
    model.eval()
    with torch.no_grad():
        x = batch['input'].to(device)
        mask = torch.nn.Transformer.generate_square_subsequent_mask(x.shape[1], device=device)
        pred = model.output(x, mask=mask, is_causal=True)
    model.train()
    return pred


def end_epoch_hook(model, epoch, loss_epoch):
    """Refresh the loss curves every epoch and the sample plots every niterplot epochs."""
    synthrat_exp.update_loss_plots(hloss, loss_epoch)
    refresh_plots(hloss, 'loss')
    if config['niterplot'] and (epoch % config['niterplot'] == 0):
        for key, dataset in (('train', train_dataset), ('val', val_dataset)):
            batch = debug_batches[key]
            synthrat_exp.update_debug_plots(
                hdebug[key], config, model, dataset, ratinabox_info,
                batch, predict_on(batch), name=key.capitalize(), nplot=3)
            refresh_plots(hdebug[key], key)


# %% [markdown]
# ## Train

# %%
if mode == 'train':
    train_args = utils.function_args_from_config(config, train)
    train_args.update({
        'train_dataloader': train_dataloader,
        'val_dataloader': val_dataloader,
        'model': model,
        'loss_epoch': loss_epoch,
        'optimizer': optimizer,
        'lr_scheduler': lr_scheduler,
        'start_epoch': epoch,
        'savefilestr': savefilestr,
        'end_epoch_hook': end_epoch_hook,
        'num_train_epochs': 100,
    })
    model, best_model, loss_epoch = train(**train_args)

# %% [markdown]
# ## Plot losses

# %%
fig, ax = plt.subplots(1, 2, figsize=(12, 4))
for key, style in (('train', '.-'), ('val', '.-')):
    if loss_epoch.get(key) is not None:
        ax[0].plot(loss_epoch[key].cpu(), style, label=key)
ax[0].set_xlabel('Epoch')
ax[0].set_ylabel('Loss')
ax[0].legend()
ax[0].set_title('Total loss')

for key in ('train_discrete', 'val_discrete'):
    if loss_epoch.get(key) is not None:
        ax[1].plot(loss_epoch[key].cpu(), '.-', label=key)
ax[1].set_xlabel('Epoch')
ax[1].legend()
ax[1].set_title('Discrete loss')
fig.tight_layout()
plt.show()

if loss_epoch.get('val') is not None:
    best = int(torch.argmin(loss_epoch['val']).item())
    print(f'best val loss {loss_epoch["val"][best].item():.4f} at epoch {best}')

# %%
# Save the final model
if mode == 'train':
    savefile = f'{savefilestr}_final.pth'
    save_model(savefile, model, lr_optimizer=optimizer, scheduler=lr_scheduler,
               loss=loss_epoch, config=config)
    print('saved', savefile)

# %% [markdown]
# ## Simulate and visualize
#
# For a few validation episodes, roll out the model open-loop `nsamples` times from
# the true initial conditions. Each rollout predicts velocity, integrates the pose,
# and recomputes the sensory input from the predicted pose; because the velocity is
# sampled from the model's predicted distribution, the samples differ. The sampled
# trajectories (colored by time) are overlaid on the ground-truth trajectory (black).

# %%
# Use the best (min val loss) model from training for evaluation.
eval_model = best_model if mode == 'train' else model

nepisodes = 3
nsamples = 10
agentspred = [0]
idxstart = np.nonzero(val_data['isstart'][:, 0])[0]   # episode start frames

gt_pose = []
pred_pose = []
with tqdm.tqdm(total=nepisodes * nsamples) as pbar:
    for epi in range(nepisodes):
        t0 = idxstart[epi] + val_dataset.context_length
        t1 = idxstart[epi + 1]
        pred_pose_ep = []
        for samplei in range(nsamples):
            pbar.set_description(f'ep {epi+1}/{nepisodes}, sample {samplei+1}/{nsamples}')
            gt_pose_ep, pred_pose_sample = synthrat_exp.simulate(
                val_dataset, eval_model, val_data['pose'],
                track_len=t1 - t0, agent_ids=agentspred, start_frame=t0,
                progress_bar=False)
            if samplei == 0:
                gt_pose.append(gt_pose_ep)
            pred_pose_ep.append(pred_pose_sample)
            pbar.update(1)
        pred_pose.append(pred_pose_ep)


# %%
def plot_example_episode_samples(pred_pose, gt_pose):
    nepisodes = len(gt_pose)
    nsamples = len(pred_pose[0])
    fig, ax = plt.subplots(1, nepisodes, figsize=(5 * nepisodes, 5),
                           sharex=True, sharey=True, squeeze=False)
    ax = ax[0]
    for epi in range(nepisodes):
        for samplei in range(nsamples):
            pred_pose_curr = pred_pose[epi][samplei][0]
            ax[epi].scatter(pred_pose_curr[:, 0], pred_pose_curr[:, 1],
                            s=15, alpha=0.5, linewidth=0.5, cmap='viridis',
                            c=np.arange(pred_pose_curr.shape[0]))
        htraj, hagent, hd = plot_episode(gt_pose[epi][0], ratinabox_info['Env'],
                                         axcurr=ax[epi], alpha=1)
        htraj.set_color('k'); hagent.set_color('k'); hd.set_color('k')
    fig.tight_layout()
    return fig, ax


fig, ax = plot_example_episode_samples(pred_pose, gt_pose)
fig.suptitle('Forecast trajectories', fontsize=16)
if outfigdir is not None:
    fig.savefig(os.path.join(outfigdir, f'synthrat_pred_traj_{timestamp}.png'), dpi=300)
    fig.savefig(os.path.join(outfigdir, f'synthrat_pred_traj_{timestamp}.pdf'), dpi=300)
plt.show()


# %% [markdown]
# ## Compare against the policy that generated the data
#
# The same plot for the original RatInABox value-function policy: from each episode's
# burn-in, run it `nsamples` times and draw where it goes. This is the reference the
# model's rollouts should be judged against — it shows how much of the spread above is
# the policy's own stochasticity rather than the model's error.
#
# The policy needs the place cells and value neuron, which the dataset cache does not
# keep, so they are rebuilt from the raw validation pickle.

# %%
with open(config['invalfile'], 'rb') as f:
    val_state = pickle.load(f)
policy = generate_data.rehydrate_policy(val_state)
print(f"rebuilt policy: {sorted(k for k in policy if policy[k] is not None)}")

# %%
# Seeds are spaced per episode so no two episodes share a sample seed.
RATINABOX_BASE_SEED = 1000
SEED_STRIDE_PER_EPISODE = 10000

pred_pose_ratinabox = []
with tqdm.tqdm(total=nepisodes) as pbar:
    for epi in range(nepisodes):
        t0 = idxstart[epi] + val_dataset.context_length
        t1 = idxstart[epi + 1]
        # The burn-in is the context the model also saw, [t0 - contextl, t0).
        burn_in_pose = val_data['pose'].array[agentspred[0],
                                              t0 - val_dataset.context_length:t0]
        samples = generate_data.run_policy_from_burn_in(
            policy, burn_in_pose=burn_in_pose,
            n_frames=gt_pose[epi].shape[1] - burn_in_pose.shape[0],
            n_samples=nsamples,
            base_seed=RATINABOX_BASE_SEED + SEED_STRIDE_PER_EPISODE * epi)
        # plot_example_episode_samples indexes [episode][sample][agent].
        pred_pose_ratinabox.append([sample[None, ...] for sample in samples])
        pbar.update(1)

for epi in range(nepisodes):
    lengths = {sample.shape[1] for sample in pred_pose_ratinabox[epi]}
    assert lengths == {gt_pose[epi].shape[1]}, \
        f'episode {epi}: policy samples are {lengths} frames, ground truth is {gt_pose[epi].shape[1]}'

# %%
fig, ax = plot_example_episode_samples(pred_pose_ratinabox, gt_pose)
fig.suptitle('RatInABox trajectories from the same initial conditions', fontsize=16)
if outfigdir is not None:
    fig.savefig(os.path.join(outfigdir, f'synthrat_ratinabox_traj_{timestamp}.png'), dpi=300)
    fig.savefig(os.path.join(outfigdir, f'synthrat_ratinabox_traj_{timestamp}.pdf'), dpi=300)
plt.show()


# %% [markdown]
# ## Animate the sampled rollouts

# %%
def make_episode_animation(pred_pose, gt_pose, out):
    nsamples = len(pred_pose)
    cmap_pred = plt.get_cmap('viridis')
    color_per_sample = np.tile(np.linspace(0.2, 0.7, nsamples)[:, None], (1, 3))

    fig, ax = plt.subplots(figsize=(5, 5))
    ratinabox_info['Env'].plot_environment(fig=fig, ax=ax, autosave=False)

    gt_traj = gt_pose[0]                    # (T, 3): x, y, theta
    T = gt_traj.shape[0]

    pred_scatters, pred_dots, pred_headings = [], [], []
    for samplei in range(nsamples):
        sc = ax.scatter([], [], s=15, alpha=0.5, linewidth=0.5,
                        cmap=cmap_pred, vmin=0, vmax=T - 1)
        sc.set_norm(Normalize(vmin=0, vmax=T - 1))
        sc.set_clim(0, T - 1)
        pred_scatters.append(sc)
        pose0 = pred_pose[samplei][0]
        dot = ax.scatter([pose0[0, 0]], [pose0[0, 1]], s=60,
                         c=color_per_sample[samplei], alpha=0.9, zorder=4, linewidth=0)
        pred_dots.append(dot)
        head = ax.quiver(pose0[0, 0], pose0[0, 1], np.cos(pose0[0, 2]), np.sin(pose0[0, 2]),
                         color=color_per_sample[samplei], alpha=0.9, zorder=4,
                         scale=15, width=0.008)
        pred_headings.append(head)

    gt_scatter = ax.scatter([], [], s=15, alpha=1, c='k', linewidth=0)
    gt_dot = ax.scatter([gt_traj[0, 0]], [gt_traj[0, 1]], s=80, c='C3', zorder=5, linewidth=0)
    gt_heading = ax.quiver(gt_traj[0, 0], gt_traj[0, 1], np.cos(gt_traj[0, 2]), np.sin(gt_traj[0, 2]),
                           color='C3', zorder=5, scale=15, width=0.012)

    def update(t):
        artists = []
        for samplei in range(nsamples):
            pose = pred_pose[samplei][0]
            pred_scatters[samplei].set_offsets(pose[:t + 1, :2])
            pred_scatters[samplei].set_array(np.arange(t + 1))
            pred_dots[samplei].set_offsets(pose[t:t + 1, :2])
            pred_headings[samplei].set_offsets(pose[t:t + 1, :2])
            pred_headings[samplei].set_UVC(np.cos(pose[t, 2]), np.sin(pose[t, 2]))
            artists.extend([pred_scatters[samplei], pred_dots[samplei], pred_headings[samplei]])
        gt_scatter.set_offsets(gt_traj[:t + 1, :2])
        gt_dot.set_offsets(gt_traj[t:t + 1, :2])
        gt_heading.set_offsets(gt_traj[t:t + 1, :2])
        gt_heading.set_UVC(np.cos(gt_traj[t, 2]), np.sin(gt_traj[t, 2]))
        artists.extend([gt_scatter, gt_dot, gt_heading])
        return artists

    anim = animation.FuncAnimation(fig, update, frames=T, interval=50, blit=False)
    anim.save(out, writer='ffmpeg', fps=20, dpi=150)
    plt.close(fig)


if outfigdir is not None:
    for epi in range(nepisodes):
        out = os.path.join(outfigdir, f'synthrat_pred_traj_ep{epi}_{timestamp}.mp4')
        make_episode_animation(pred_pose[epi], gt_pose[epi], out)
        print('saved', out)
